
// This file has been generated by the GUI designer. Do not modify.
namespace Chess
{
	public partial class Graphics
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Chess.Graphics
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Chess.Graphics";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
